# Generated by Django 5.0.6 on 2024-05-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DairyProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecomapp.product",
                    ),
                ),
                ("expiry_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "dairyProduct",
            },
            bases=("ecomapp.product",),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
